= Introduction
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::rootdir[:rootdir: ./]
ifndef::source-highlighter[:source-highlighter: coderay]
:imagesdir: {rootdir}

This document contains a tutorial for getting started with the query and transformation development in VIATRA.

The tutorial relies on the CPS Demonstrator application from https://github.com/IncQueryLabs/incquery-examples-cps. The CPS Demonstrator is specified to cover a usual workflow in Model-driven Engineering, where a system is (1) first described in a source domain model, then (2) automated model-to-model transformations are used to derive a target domain model. Finally, (3) model-to-text transformation is performed to generate code from the target domain. In addition, a model generator that can automatically create source domain models can support the correctness testing and performance evaluation of the components.

This tutorial uses only a subset of the transformation, as its main goal is to illustrate the basics of the VIATRA environment; while a few additional steps were added to illustrate additional capabilities of the framework. Consult the original demonstrator for a more complex transformation example.

This document starts with a quick setup guide, then describes model query development. Both batch and incremental transformations are covered later. Finally, a few advanced features such as the API of the event-driven virtual machine or UI integration support is introduced shortly.
